// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wikxuqigcmkvtfcappyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpa3h1cWlnY21rdnRmY2FwcHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3OTAzNjYsImV4cCI6MjA1NDM2NjM2Nn0.ME7nyohKittyF0xX91T2Fy5CbXy22VBwqJO8e1ze2ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);